version: "3"
services:
  node:
    build: ./docker/node
    container_name: fortune-js
    volumes:
      - ./data/node:/app
    environment:
      - NODE_ENV=development
    links:
      - "db:db"
    networks:
      fortune-backend:
        ipv4_address: 172.22.0.3
  db:
    build: ./docker/mongo
    container_name: fortune-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: redacted
      MONGO_INITDB_ROOT_PASSWORD: redacted
networks:
  fortune-backend:
    driver: bridge
    ipam:
      config:
      - subnet: 172.22.0.0/24